### ISSUE TITLE
Discrepency with Freyja

### ISSUE THREAD

**Issue by EricFournier3** [Ellmen/alcov#62]
Hi,

we performed a comparison between Alcov (1.1.28) and Frejya and found  some cases where variants found with Freyja (for example, LB, LK, LD, LF and KS) are never found with Alcov. However, I can see those variants in the alcov/alcov/lineages.txt

Do you have a possible explanation for this observation?

I attached results from both tools here 

Thanks
[Freyja_Alcov_Compare.zip](https://github.com/user-attachments/files/15794043/Freyja_Alcov_Compare.zip)

Eric

**Comment by JennKnapp** [comment]
Hi there, 
Thanks for your question! The list in alcov/alcov/lineages.txt is pulled from the [pango-designation github](https://raw.githubusercontent.com/cov-lineages/pango-designation/master/lineage_notes.txt) (which is the same place Freyja would get their list from), but when building the mutation constellations that alcov uses for lineage calls, we compare the list (lineages.txt) to the publicly available sequences in genbank. If there are at least 100 sequences available for a lineage in genbank then we make a mutation constellation for that lineage. This usually means that brand new lineages will not have a constellation built until they pass this threshold.

You can see which lineages alcov is able to call by checking in "alcov/alcov/data/constellations/", so if there is no constellation file here for a specific lineage, then alcov will never call it.

Let me know if you need more clarification!

Thanks, 
Jenn

**Comment by EricFournier3** [comment]
Great,

thank you Jenn
